name: Build Multi-Platform Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Build application
        run: |
          pyinstaller --onefile --windowed --name CorrectionRequest main.py
      
      # macOSの実行権限付与
      - name: Make executable (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          chmod +x dist/CorrectionRequest
          xattr -cr dist/CorrectionRequest
      
      - uses: actions/upload-artifact@v4
        with:
          name: CorrectionRequest-${{ matrix.os }}
          path: dist/*
